services:
  mongo:
    env_file:
      - ../.env
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ../volumes/db:/data/db
      - ../volumes/configdb:/data/configdb
  mongo-express:
    env_file:
      - ../.env
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
